### ISSUE TITLE
Unexpected token * when calling scrapeAll

### ISSUE THREAD

**Issue by adamwlarson** [TMiguelT/pokemontcgscraper#3]
I am using node version 0.12.6.

I am doing this initial test:
	var scraper = require("pokemon-tcg-scraper");
        scraper.scrapeAll({
            cardName: "saur"
        }, false).then(function (cards) {
            res.json(cards);
        }).catch(function(err){
        	done(err);
        });

I get an error in index.js line 32 return co(function *() {

Any ideas why this is happening?

**Comment by TMiguelT** [comment]
I think it's throwing a syntax error because my code is using generators.

Either you'll need to use a newer version of node like 4.2 or 5 (which I recommend anyway), or you'll need to [run node in harmony mode](http://stackoverflow.com/a/28663963/2148718).

**Comment by TMiguelT** [comment]
I'm assuming that this worked, so I'll close the issue.
